# Generated by Django 4.2.3 on 2023-08-31 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.\\-_]+$', message='Username must contain only letters, numbers, underscore, dot or dash character')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
